<?php

/**
 * @file
 * Provides INFOBIP implementation methods.
 */

/**
 * Implements hook_gateway_info().
 */
function infobip_gateway_info() {
  return array(
    'infobip' => array(
      'name' => 'Infobip',
      'send' => 'infobip_send',
      'receive' => TRUE,
      'configure form' => 'infobip_admin_form',
      'send form' => 'infobip_send_form',
    ),
  );
}

/**
 * Implements hook_menu().
 */
function infobip_menu() {
  $items = array();
  $items['admin/smsframework/gateways/infobip'] = array(
    'title' => 'Infobip Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('infobip_admin_form'),
    'access arguments' => array('administer infobipsmsgateway'),
    'file' => 'infobip.admin.inc',
  );
  $items['sms/infobip/inbound'] = array(
    'title' => 'Infobip SMS message receiver',
    'page callback' => 'infobip_receive_message',
    'access arguments' => array('administer infobipsmsgateway'),
  );
  $items['sms/infobip/receipt'] = array(
    'title' => 'Infobip SMS receipt receiver',
    'page callback' => 'infobop_receive_receipt',
    'access arguments' => array('administer infobipsmsgateway'),
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function infobip_permission() {
  return array(
    'administer infobipsmsgateway' => array(
      'title' => t('Administer Infobop SMS Gateway'),
      'description' => t('Infobip SMS Gateway Inbound and Receipt access'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function infobip_form_sms_admin_default_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['Infobip']['id']['#markup']) && $form['Infobip']['id']['#markup'] == 'infobip') {
    $form['Infobip']['configure']['#markup'] = l(t('configure'), 'admin/smsframework/gateways/infobip');
  }
}

/**
 * Implements hook_help().
 */
function infobip_help($path, $arg) {
  switch ($path) {
    case 'admin/help#infobip':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Infobip SMS Gateway module provides an integration between <a href="https://www.infobip.com" target="_blank">Infobip SMS</a> service and <a href="https://www.drupal.org/project/smsframework" target="_blank">SMS framework</a> module.') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<p>' . t('This module requires INFOBIP subscription. <a href="http://www.infobip.com/en/get-started" target="_blank">Click here</a> to sign-up with INFOBIP.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_send().
 */
function infobip_send($number, $message, $options = array()) {
  $config = array();
  $config['infobip_username'] = variable_get('infobip_username', '');
  $config['infobip_password'] = variable_get('infobip_password', '');
  $config['infobip_sender'] = variable_get('infobip_sender', '');
  if ($unicode_message = infobip_unicode($message)) {
    $message = $unicode_message;
  }
  else {
    $message = rawurlencode($message);
  }
  $number = isset($options['country']) ? $options['country'] . $number : $number;
  $username = !empty($config['infobip_username']) ? $config['infobip_username'] : '';
  $password = !empty($config['infobip_password']) ? $config['infobip_password'] : '';
  $from = !empty($config['infobip_sender']) ? $config['infobip_sender'] : 'SMS';

  $api_send_url = 'https://api.infobip.com/sms/1/text/query';
  $query = 'username=' . $username . '&password=' . $password . '&from=' . $from . '&to=' . $number . '&text=' . $message ;
  $http_result = drupal_http_request($api_send_url . '?' . $query);
  //add infobip http header with base64 encoded

  if (isset($http_result->error)) {
    return array(
      'status' => FALSE,
      'message' => 'An error occurred during the HTTP request: @error', array(
        '@error' => $http_result->error,
      ),
    );
  }
  if (isset($http_result->data)) {
    if (strpos($http_result->data, 'ERR') !== FALSE) {
      $result = array(
        'status' => FALSE,
        'message' => $http_result->data,
      );
    }
    else {
      $result = array(
        'status' => TRUE,
        'data' => $http_result->data,
      );
    }
  }
  return $result;
}

/**
 * Receive an SMS message and pass it into the SMS Framework.
 */
function infobip_receive_message() {
  if (!isset($_REQUEST['text'], $_REQUEST['msisdn'], $_REQUEST['to'])) {
    return FALSE;
  }
  else {
    $number = $_REQUEST['msisdn'];
    $message = $_REQUEST['text'];
    $options = array();
    if (array_key_exists('to', $_REQUEST) && !empty($_REQUEST['to'])) {
      $options['receiver'] = $_REQUEST['to'];
    }
    if (array_key_exists('network-code', $_REQUEST) && !empty($_REQUEST['network-code'])) {
      $options['network-code'] = $_REQUEST['network-code'];
    }
    if (array_key_exists('message-timestamp', $_REQUEST) && !empty($_REQUEST['message-timestamp'])) {
      $options['message-timestamp'] = $_REQUEST['message-timestamp'];
    }
    if (array_key_exists('messageId', $_REQUEST) && !empty($_REQUEST['messageId'])) {
      $options['messageId'] = $_REQUEST['messageId'];
    }
    sms_incoming($number, $message, $options);
    print "response 200 OK";
  }
}

/**
 * Receive a message send receipt from Infobip.
 */
function infobip_receive_receipt() {
  $number = $_REQUEST['msisdn'];
  $gateway_status = $_REQUEST['status'];
  $reference = (array_key_exists('messageId', $_REQUEST)) ? $_REQUEST['messageId'] : NULL;
  $options = array();
  $options['reference'] = $reference;
  if (array_key_exists('to', $_REQUEST) && !empty($_REQUEST['to'])) {
    $options['receiver'] = $_REQUEST['to'];
  }
  if (array_key_exists('network-code', $_REQUEST) && !empty($_REQUEST['network-code'])) {
    $options['network-code'] = $_REQUEST['network-code'];
  }
  if (array_key_exists('price', $_REQUEST) && !empty($_REQUEST['price'])) {
    $options['price'] = $_REQUEST['price'];
  }
  if (array_key_exists('messageId', $_REQUEST) && !empty($_REQUEST['messageId'])) {
    $options['messageId'] = $_REQUEST['messageId'];
  }
  sms_receipt($number, $reference, $gateway_status, $options);
  print "response 200 OK";
}

/**
 * Returns custom additions to be added to the send forms.
 */
function infobip_send_form() {
  $options = array(
    "" => "- Select Country -",
  ) + sms_country_codes();
  $form['country'] = array(
    '#type' => 'select',
    '#title' => t('Country'),
    '#multiple' => FALSE,
    '#options' => $options,
    '#default_value' => -1,
    '#required' => TRUE,
  );
  return $form;
}

/**
 * Converts a string to UCS-2 encoding if necessary.
 */
function infobip_unicode($message) {
  if (function_exists('iconv')) {
    $latin = @iconv('UTF-8', 'ISO-8859-1', $message);
    if (strcmp($latin, $message)) {
      $arr = unpack('H*hex', @iconv('UTF-8', 'UCS-2BE', $message));
      return strtoupper($arr['hex']) . '&unicode=1';
    }
  }
  return FALSE;
}
